#!/usr/bin/env python3
"""Shared typography for the paper figures (IEEE/IROS two-column style).

Single source of truth so figures regenerated by different scripts stay
typographically identical: Times text, STIX math, upright (never bold)
subplot captions placed below the panel they describe.

**These point sizes only survive to the page if the figure is authored at the
width it is placed at.** LaTeX scales the PDF to the \\includegraphics width,
and the fonts scale with it — a 7 in figure dropped into a 3.5 in column has
every label halved. Figs 5-9 are all single-column in the paper, so author
them at COLUMN_W and let \\includegraphics[width=\\columnwidth] be a no-op.
Check with `python tools/check_figure_scale.py` after regenerating.
"""

# IEEEtran \columnwidth; \textwidth (a figure* spread) is 7.16 in
COLUMN_W = 3.5

PAPER_RC = {
    'font.family': 'serif',
    'font.serif': ['Times New Roman', 'Times', 'DejaVu Serif'],
    'mathtext.fontset': 'stix',
    'font.size': 8,
    'axes.labelsize': 9,
    'axes.titlesize': 9,
    'xtick.labelsize': 8,
    'ytick.labelsize': 8,
    'legend.fontsize': 6.5,
    'pdf.fonttype': 42,
    'ps.fonttype': 42,
}

CAPTION_SIZE = 9


def panel_caption(ax, text, pad=None):
    """Place an '(a) ...' caption centred below `ax`, upright, not bold.

    pad is the gap in points from the axes bottom. The default clears
    whatever the panel actually carries below its frame, so a caption sits
    the same distance under the last element in every panel whether or not
    that panel has tick labels (shared axes) or an xlabel. Call this after
    set_xlabel() and any tick_params(labelbottom=...).
    """
    if pad is None:
        pad = 8.0
        if any(lbl.get_visible() for lbl in ax.get_xticklabels()):
            pad += 12.0
        if ax.get_xlabel():
            pad += 14.0
    return ax.annotate(text, xy=(0.5, 0.0), xycoords='axes fraction',
                       xytext=(0.0, -pad), textcoords='offset points',
                       ha='center', va='top', fontsize=CAPTION_SIZE,
                       fontweight='normal', annotation_clip=False)
